services:
  server:
    build:
      context: .
    user: "1000:1000"
    environment:
      NODE_ENV: production
      PORT: 4000
      FRONTEND_URL: ${FRONTEND_URL}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_PUBLISHABLE_KEY: ${SUPABASE_PUBLISHABLE_KEY}
    ports:
      - 4000:4000